[colors]
foreground = "#E0CCAE"
background = "#1a1b26"
cursor_bg = "#E0CCAE"
cursor_border = "#E0CCAE"
cursor_fg = "#1a1b26"
selection_bg = "#714f41"
selection_fg = "#E0CCAE"
split = "#d47d49"
compose_cursor = "#ff9e64"

ansi = ["#15161e", "#bf472c", "#a4896f", "#f2a766", "#d47d49", "#8a4b53", "#a67458", "#F2A766"]
brights = ["#392D2B", "#bf472c", "#a4896f", "#f2a766", "#d47d49", "#8a4b53", "#a67458", "#E0CCAE"]

[colors.tab_bar]
inactive_tab_edge = "#16161e"
background = "#1a1b26"

[colors.tab_bar.active_tab]
fg_color = "#16161e"
bg_color = "#d47d49"

[colors.tab_bar.inactive_tab]
fg_color = "#66292F"
bg_color = "#241816"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#d47d49"
bg_color = "#241816"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#d47d49"
bg_color = "#1a1b26"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#d47d49"
bg_color = "#1a1b26"

[metadata]
aliases = []
author = "folke"
name = "faroutnight"