[colors]
foreground = "#6c6252"
background = "#e1e2e7"
cursor_bg = "#6c6252"
cursor_border = "#6c6252"
cursor_fg = "#e1e2e7"
selection_bg = "#c48c75"
selection_fg = "#6c6252"
split = "#c77544"
compose_cursor = "#b15c00"

ansi = ["#e9e9ed", "#db5234", "#715e4b", "#9b6635", "#c77544", "#c37f87", "#91654c", "#9b6635"]
brights = ["#d1c4c2", "#db5234", "#715e4b", "#9b6635", "#c77544", "#c37f87", "#91654c", "#6c6252"]

[colors.tab_bar]
inactive_tab_edge = "#e9e9ec"
background = "#e1e2e7"

[colors.tab_bar.active_tab]
fg_color = "#e9e9ec"
bg_color = "#c77544"

[colors.tab_bar.inactive_tab]
fg_color = "#dfa9ad"
bg_color = "#eae1e0"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#c77544"
bg_color = "#eae1e0"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#c77544"
bg_color = "#e1e2e7"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#c77544"
bg_color = "#e1e2e7"

[metadata]
aliases = []
author = "folke"
name = "faroutday"