attribute = { fg = "#91654c" }
comment = { fg = "#d79687", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "#9b6635" }
constant = { fg = "#b15c00" }
"constant.builtin" = { fg = "#db5234" }
"constant.builtin.boolean" = { fg = "#b15c00" }
"constant.character" = { fg = "#715e4b" }
"constant.character.escape" = { fg = "#c37f87" }
"constant.numeric" = { fg = "#b15c00" }
"constant.numeric.float" = { fg = "#b15c00" }
"constant.numeric.integer" = { fg = "#b15c00" }
constructor = { fg = "#db5234" }
"diagnostic.error" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diff.delta" = { fg = "#dfa9ad" }
"diff.delta.moved" = { fg = "#c77544" }
"diff.minus" = { fg = "#db5234" }
"diff.plus" = { fg = "#725f3e" }
error = { fg = "#a14834" }
function = { fg = "#c77544" }
"function.builtin" = { fg = "#db5234" }
"function.macro" = { fg = "#91654c" }
"function.method" = { fg = "#c77544" }
"function.special" = { fg = "#91654c" }
hint = { fg = "#a27961" }
info = { fg = "#725f3e" }
keyword = { fg = "#876060", modifiers = ["italic"] }
"keyword.control" = { fg = "#c37f87" }
"keyword.control.conditional" = { fg = "#c37f87" }
"keyword.control.exception" = { fg = "#c37f87" }
"keyword.control.repeat" = { fg = "#c37f87" }
"keyword.control.return" = { fg = "#876060", modifiers = ["italic"] }
"keyword.directive" = { fg = "#91654c" }
"keyword.function" = { fg = "#c37f87" }
"keyword.operator" = { fg = "#c37f87" }
label = { fg = "#c77544" }
"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = { fg = "#c77544", modifiers = ["bold"] }
"markup.heading.completion" = { bg = "#f0e9e8", fg = "#6c6252" }
"markup.heading.hover" = { bg = "#dcaa9f" }
"markup.italic" = { modifiers = ["italic"] }
"markup.link" = { fg = "#c77544", underline = { style = "line" } }
"markup.link.label" = { fg = "#a27961" }
"markup.link.text" = { fg = "#a27961" }
"markup.link.url" = { underline = { style = "line" } }
"markup.list" = { fg = "#b15c00", modifiers = ["bold"] }
"markup.normal.completion" = { fg = "#d79687" }
"markup.normal.hover" = { fg = "#9b6635" }
"markup.raw" = { fg = "#a27961" }
"markup.raw.block" = { fg = "#a27961" }
"markup.raw.inline" = { bg = "#d1c4c2", fg = "#c77544" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
namespace = { fg = "#c37f87" }
operator = { fg = "#91654c" }
special = { fg = "#db5234" }
string = { fg = "#715e4b" }
"string.regexp" = { fg = "#a47d6a" }
"string.special" = { fg = "#db5234" }
tag = { fg = "#c37f87" }
type = { fg = "#db5234" }
"type.builtin" = { fg = "#f06c53" }
"type.enum" = { fg = "#db5234" }
"type.enum.variant" = { fg = "#b15c00" }
"ui.background" = { bg = "bg" }
"ui.cursor" = { bg = "#6c6252", fg = "#f9f6f6" }
"ui.cursor.match" = { fg = "#b15c00", modifiers = ["bold"] }
"ui.linenr" = { fg = "#d79687" }
"ui.linenr.select" = { fg = "#91654c" }
"ui.menu" = { bg = "#f0e9e8", fg = "#6c6252" }
"ui.menu.scroll" = { bg = 14866646, fg = 14128775 }
"ui.menu.selected" = { bg = "#dcaa9f" }
"ui.popup" = { bg = "#f0e9e8", fg = "#f06c53" }
"ui.selection" = { bg = "bg_highlight" }
"ui.statusline" = { bg = "#f0e9e8", fg = "#9b6635" }
"ui.statusline.inactive" = { bg = "#f0e9e8", fg = "#d79687" }
"ui.statusline.normal" = { bg = "blue", fg = "black" }
"ui.text" = { bg = "#f9f6f6", fg = "#6c6252" }
"ui.text.focus" = { bg = "#dd9169" }
"ui.text.inactive" = { fg = "#d79687", modifiers = ["italic"] }
"ui.text.info" = { bg = "#f0e9e8", fg = "#6c6252" }
"ui.virtual.inlay-hint" = { bg = "#f3efee", fg = "#a27961" }
"ui.window" = { fg = "#faf8f8", modifiers = ["bold"] }
variable = { fg = "#6c6252" }
"variable.builtin" = { fg = "#db5234" }
"variable.other.member" = { fg = "#887562" }
"variable.parameter" = { fg = "#9b6635" }
warning = { fg = "#9b6635" }

[palette]
bg = "#f9f6f6"
bg_dark = "#f0e9e8"
bg_float = "#f0e9e8"
bg_highlight = "#eae1e0"
bg_popup = "#f0e9e8"
bg_search = "#aa6330"
bg_sidebar = "#f0e9e8"
bg_statusline = "#f0e9e8"
bg_visual = "#dd9169"
black = "#faf8f8"
blue = "#c77544"
blue0 = "#aa6330"
blue1 = "#db5234"
blue2 = "#725f3e"
blue5 = "#91654c"
blue6 = "#a47d6a"
blue7 = "#e88f6a"
border = "#faf8f8"
border_highlight = "#f06c53"
comment = "#d79687"
cyan = "#91654c"
dark3 = "#dfa9ad"
dark5 = "#91654c"
"delta.add" = "#ab927e"
"delta.delete" = "#e69c91"
"diff.add" = "#e2d3cb"
"diff.change" = "#f4ebe9"
"diff.delete" = "#f0dcd9"
"diff.text" = "#e88f6a"
error = "#a14834"
fg = "#6c6252"
fg_dark = "#9b6635"
fg_float = "#6c6252"
fg_gutter = "#d79687"
fg_sidebar = "#9b6635"
"git.add" = "#725f3e"
"git.change" = "#dfa9ad"
"git.delete" = "#db5234"
"git.ignore" = "#dfa9ad"
"gitSigns.add" = "#847254"
"gitSigns.change" = "#be7c82"
"gitSigns.delete" = "#da6b52"
green = "#715e4b"
green1 = "#887562"
green2 = "#806e5e"
hint = "#a27961"
info = "#725f3e"
magenta = "#c37f87"
magenta2 = "#9b6169"
orange = "#b15c00"
purple = "#876060"
red = "#db5234"
red1 = "#a14834"
teal = "#a27961"
terminal_black = "#d1c4c2"
todo = "#c77544"
warning = "#9b6635"
yellow = "#9b6635"